Myfile = open("coding.txt", "w")
Myfile.write("Coding is basically the computer language used to develop apps, websites, and software.\n")
Myfile.write("Without it, we’d have none of the most popular technology we’ve come to rely on such as Facebook, our smartphones,\n")
Myfile.write("the browser.\n")
Myfile.write("It all runs on code.\n")
Myfile.write("It all runs on code.\n")
Myfile.write("To go a bit deeper, computers don’t understand words.\n")
Myfile.write("They only understand the concepts of on and off.\n")
Myfile.write("Binary code represents these on and off signals as the digits 1 and 0.\n")
Myfile.write("In order to make binary code manageable, computer programming languages were formed.\n")
Myfile.close()

Myfile = open("coding.txt", "r")
content = Myfile.read()
print(content)
Myfile.close()